import type { Weapon } from "../calculator/weapon";

const weaponNameToWeight: Record<Weapon["name"], number> = {
  "Academy Glintstone Staff": 3,
  "Alabaster Lord's Sword": 8,
  "Albinauric Bow": 4.5,
  "Albinauric Staff": 2.5,
  "Ancient Meteoric Ore Greatsword": 22,
  "Ansbach's Longbow": 4.5,
  "Antspur Rapier": 3,
  "Anvil Hammer": 22,
  Arbalest: 6,
  "Astrologer's Staff": 3,
  "Axe of Godfrey": 18,
  "Axe of Godrick": 11,
  "Azur's Glintstone Staff": 4,
  "Backhand Blade": 2,
  "Bandit's Curved Sword": 5,
  "Banished Knight's Greatsword": 10,
  "Banished Knight's Halberd": 8,
  "Barbed Staff-Spear": 7.5,
  "Bastard Sword": 9,
  "Bastard's Stars": 5.5,
  "Battle Axe": 4.5,
  "Battle Hammer": 10,
  "Beast Claw": 3,
  "Beast-Repellent Torch": 2.5,
  "Beastclaw Greathammer": 9,
  "Beastman's Cleaver": 16.5,
  "Beastman's Curved Sword": 4,
  "Black Bow": 4,
  "Black Knife": 2,
  "Black Steel Greathammer": 12,
  "Black Steel Twinblade": 8,
  "Blade of Calling": 1.5,
  "Blasphemous Blade": 13.5,
  "Bloodfiend's Arm": 20,
  "Bloodfiend's Fork": 4.5,
  "Bloodfiend's Sacred Spear": 8,
  "Bloodhound Claws": 3,
  "Bloodhound's Fang": 11.5,
  "Bloodstained Dagger": 2,
  "Bloody Helice": 8,
  "Bolt of Gransax": 8.5,
  "Bone Bow": 3,
  "Bonny Butchering Knife": 8.5,
  "Brick Hammer": 12.5,
  Broadsword: 4,
  "Butchering Knife": 8.5,
  Caestus: 1.5,
  "Cane Sword": 2.5,
  "Carian Glintblade Staff": 2.5,
  "Carian Glintstone Staff": 3,
  "Carian Knight's Sword": 4,
  "Carian Regal Scepter": 3,
  "Carian Sorcery Sword": 2.5,
  "Carian Thrusting Shield": 10.5,
  "Celebrant's Cleaver": 4.5,
  "Celebrant's Rib-Rake": 5,
  "Celebrant's Sickle": 1.5,
  "Celebrant's Skull": 8.5,
  "Chainlink Flail": 8,
  "Chilling Perfume Bottle": 1,
  Cinquedea: 3.5,
  "Cipher Pata": 0,
  "Clawmark Seal": 1.5,
  "Claws of Night": 3,
  "Clayman's Harpoon": 5.5,
  Claymore: 9,
  "Cleanrot Knight's Sword": 4,
  "Cleanrot Spear": 5.5,
  "Clinging Bone": 3,
  Club: 3.5,
  "Coded Sword": 2.5,
  "Commander's Standard": 11.5,
  "Composite Bow": 3,
  "Cranial Vessel Candlestand": 12.5,
  "Crepus's Black-Key Crossbow": 5,
  "Crescent Moon Axe": 12.5,
  "Cross-Naginata": 8,
  "Crystal Knife": 2,
  "Crystal Spear": 5.5,
  "Crystal Staff": 4.5,
  "Crystal Sword": 4.5,
  "Curseblade's Cirque": 4.5,
  "Curved Club": 5,
  "Curved Great Club": 10,
  Dagger: 1.5,
  "Dancing Blade of Ranah": 3.5,
  "Dane's Footwork": 1,
  "Dark Moon Greatsword": 10,
  "Deadly Poison Perfume Bottle": 1,
  "Death Knight's Longhaft Axe": 11.5,
  "Death Knight's Twin Axes": 5.5,
  "Death Ritual Spear": 6.5,
  "Death's Poker": 8.5,
  "Demi-Human Queen's Staff": 3,
  "Devonia's Hammer": 20,
  "Devourer's Scepter": 11.5,
  "Digger's Staff": 4.5,
  Dismounter: 10,
  "Dragon Communion Seal": 0,
  "Dragon Greatclaw": 16,
  "Dragon Halberd": 10.5,
  "Dragon King's Cragblade": 8,
  "Dragon-Hunter's Great Katana": 10.5,
  "Dragonscale Blade": 5.5,
  "Dryleaf Arts": 1,
  "Dryleaf Seal": 1.5,
  "Dueling Shield": 9,
  "Duelist Greataxe": 20,
  "Eclipse Shotel": 3,
  "Eleonora's Poleblade": 6,
  "Envoy's Greathorn": 19.5,
  "Envoy's Horn": 4,
  "Envoy's Long Horn": 9.5,
  "Erdsteel Dagger": 2,
  "Erdtree Bow": 4,
  "Erdtree Greatbow": 11,
  "Erdtree Seal": 0,
  Estoc: 4.5,
  Euporia: 8.5,
  "Executioner's Greataxe": 15,
  Falchion: 3.5,
  "Fallingstar Beast Jaw": 21.5,
  Falx: 4,
  "Family Heads": 5.5,
  "Finger Seal": 1.5,
  "Fire Knight's Greatsword": 16,
  "Fire Knight's Seal": 1.5,
  "Fire Knight's Shortsword": 2,
  "Firespark Perfume Bottle": 1,
  Flail: 5,
  Flamberge: 10,
  "Flowerstone Gavel": 6,
  "Flowing Curved Sword": 3.5,
  "Forked Greatsword": 9,
  "Forked Hatchet": 2.5,
  "Forked-Tongue Hatchet": 4,
  "Frenzied Flame Seal": 0,
  "Frenzyflame Perfume Bottle": 1,
  "Freyja's Greatsword": 14,
  "Frozen Needle": 2.5,
  "Full Moon Crossbow": 4,
  "Gargoyle's Black Axe": 8.5,
  "Gargoyle's Black Blades": 8.5,
  "Gargoyle's Black Halberd": 12,
  "Gargoyle's Blackblade": 11.5,
  "Gargoyle's Great Axe": 8.5,
  "Gargoyle's Greatsword": 11.5,
  "Gargoyle's Halberd": 12,
  "Gargoyle's Twinblade": 8.5,
  "Gazing Finger": 15,
  "Gelmir Glintstone Staff": 2.5,
  "Ghiza's Wheel": 19,
  "Ghostflame Torch": 2.5,
  "Giant's Red Braid": 2.5,
  "Giant's Seal": 1.5,
  "Giant-Crusher": 26.5,
  Glaive: 10,
  "Glintstone Kris": 1.5,
  "Glintstone Staff": 3,
  "Godskin Peeler": 8,
  "Godskin Stitcher": 7,
  "Godslayer's Greatsword": 17.5,
  "Godslayer's Seal": 1.5,
  "Golden Epitaph": 3.5,
  "Golden Halberd": 13.5,
  "Golden Order Greatsword": 10,
  "Golden Order Seal": 0,
  "Golem Fist": 5,
  "Golem Greatbow": 14.5,
  "Golem's Halberd": 21.5,
  "Grafted Blade Greatsword": 21,
  "Grafted Dragon": 2.5,
  "Grave Scythe": 9.5,
  "Gravel Stone Seal": 1.5,
  "Great Club": 17,
  "Great Katana": 9,
  "Great Knife": 1.5,
  "Great Mace": 11.5,
  "Great Omenkiller Cleaver": 11,
  "Great Stars": 10,
  "Great Épée": 6.5,
  Greataxe: 13,
  Greatbow: 10,
  "Greathorn Hammer": 10,
  Greatsword: 23,
  "Greatsword of Damnation": 8,
  "Greatsword of Radahn (Light)": 20,
  "Greatsword of Radahn (Lord)": 16,
  "Greatsword of Solitude": 15.5,
  Grossmesser: 4.5,
  "Guardian's Swordspear": 9,
  Halberd: 8,
  "Halo Scythe": 8.5,
  Hammer: 6.5,
  "Hand Axe": 3.5,
  "Hand Ballista": 10,
  "Hand of Malenia": 7,
  "Harp Bow": 2,
  "Heavy Crossbow": 5.5,
  "Helphen's Steeple": 11.5,
  "Highland Axe": 4.5,
  Hookclaws: 2,
  "Horn Bow": 4.5,
  "Horned Warrior's Greatsword": 13,
  "Horned Warrior's Sword": 5,
  "Hoslow's Petal Whip": 3.5,
  "Icerind Hatchet": 3,
  "Igon's Greatbow": 12.5,
  "Inquisitor's Girandole": 7.5,
  "Inseparable Sword": 10,
  "Iron Ball": 2.5,
  "Iron Cleaver": 6,
  "Iron Greatsword": 12,
  "Iron Spear": 4.5,
  "Ivory Sickle": 2,
  "Jar Cannon": 15,
  "Jawbone Axe": 5.5,
  Katar: 2.5,
  "Knight's Greatsword": 10,
  "Lamenting Visage": 2,
  Lance: 9,
  "Large Club": 8.5,
  "Lazuli Glintstone Sword": 3.5,
  "Leda's Sword": 7.5,
  "Light Crossbow": 4,
  "Lightning Perfume Bottle": 1,
  "Lion Greatbow": 9.5,
  "Lizard Greatsword": 9.5,
  Longbow: 4,
  "Longhaft Axe": 12.5,
  Longsword: 3.5,
  "Lordsworn's Greatsword": 9,
  "Lordsworn's Straight Sword": 3.5,
  "Loretta's War Sickle": 10,
  Lucerne: 7,
  "Lusat's Glintstone Staff": 4,
  Mace: 4.5,
  "Madding Hand": 1,
  "Magma Blade": 4,
  "Magma Whip Candlestick": 2.5,
  "Magma Wyrm's Scalesword": 15,
  "Main-gauche": 2.5,
  "Maliketh's Black Blade": 22,
  "Mantis Blade": 4,
  "Marais Executioner's Sword": 11.5,
  "Marika's Hammer": 6,
  "Maternal Staff": 2.5,
  "Messmer Soldier's Axe": 5.5,
  "Messmer Soldier's Spear": 8.5,
  "Meteoric Ore Blade": 7.5,
  "Meteorite Staff": 4.5,
  Milady: 6.5,
  "Miquellan Knight's Sword": 3.5,
  "Misbegotten Shortbow": 3,
  Miséricorde: 2,
  "Mohgwyn's Sacred Spear": 10,
  "Monk's Flameblade": 9,
  "Monk's Flamemace": 6,
  "Moonrithyll's Knight Sword": 18,
  Moonveil: 6.5,
  "Morgott's Cursed Sword": 7.5,
  "Morning Star": 5,
  Nagakiba: 7,
  "Nanaya's Torch": 3.5,
  "Nightrider Flail": 6,
  "Nightrider Glaive": 12,
  "Noble's Estoc": 3.5,
  "Noble's Slender Sword": 3.5,
  "Nox Flowing Hammer": 6.5,
  "Nox Flowing Sword": 3.5,
  "Obsidian Lamina": 6.5,
  "Omen Cleaver": 11.5,
  "Onyx Lord's Greatsword": 11.5,
  "Ordovis's Greatsword": 12,
  "Ornamental Straight Sword": 3,
  "Parrying Dagger": 1.5,
  Partisan: 6.5,
  Pata: 4,
  "Pest's Glaive": 7,
  Pickaxe: 10,
  Pike: 7.5,
  "Poisoned Hand": 1,
  "Poleblade of the Bud": 10,
  "Prelate's Inferno Crozier": 23.5,
  "Prince of Death's Staff": 3,
  "Pulley Bow": 5,
  "Pulley Crossbow": 4,
  "Putrescence Cleaver": 13.5,
  "Queelign's Greatsword": 7.5,
  "Rabbath's Cannon": 15,
  "Rakshasa's Great Katana": 9.5,
  Rapier: 2.5,
  "Raptor Talons": 1.5,
  "Red Bear's Claw": 4,
  "Red Branch Shortbow": 2.5,
  Reduvia: 2.5,
  "Regalia of Eochaid": 5.5,
  "Rellana's Twin Blades": 8,
  "Repeating Crossbow": 6,
  "Ringed Finger": 4.5,
  "Ripple Blade": 4.5,
  "Ripple Crescent Halberd": 8.5,
  "Rivers of Blood": 6.5,
  "Rogier's Rapier": 3.5,
  "Rosus' Axe": 5.5,
  "Rotten Battle Hammer": 10,
  "Rotten Crystal Spear": 5.5,
  "Rotten Crystal Staff": 4.5,
  "Rotten Crystal Sword": 4.5,
  "Rotten Greataxe": 20,
  "Rotten Staff": 18,
  "Royal Greatsword": 20,
  "Ruins Greatsword": 23,
  "Rusted Anchor": 12.5,
  "Sacred Relic Sword": 11,
  "Sacrificial Axe": 5.5,
  "Scavenger's Curved Sword": 3.5,
  "Scepter of the All-Knowing": 4.5,
  Scimitar: 3,
  "Scorpion's Stinger": 2.5,
  Scythe: 7.5,
  "Sentry's Torch": 5,
  "Serpent Bow": 3.5,
  "Serpent Flail": 6,
  "Serpent-God's Curved Sword": 4,
  "Serpent-Hunter": 12,
  "Serpentbone Blade": 6,
  "Shadow Sunflower Blossom": 16,
  Shamshir: 3.5,
  "Short Spear": 4,
  "Short Sword": 3,
  Shortbow: 2.5,
  Shotel: 2,
  "Siluria's Tree": 10,
  "Smithscript Axe": 5,
  "Smithscript Cirque": 2,
  "Smithscript Dagger": 1.5,
  "Smithscript Greathammer": 9,
  "Smithscript Spear": 4,
  "Soldier's Crossbow": 3.5,
  Spear: 4.5,
  "Spear of the Impaler": 9.5,
  "Spiked Caestus": 2,
  "Spiked Club": 5,
  "Spiked Spear": 6,
  "Spiraltree Seal": 1.5,
  "Spirit Glaive": 6.5,
  "Spirit Sword": 2.5,
  "Spread Crossbow": 5,
  "St. Trina's Torch": 3,
  "Staff of Loss": 2.5,
  "Staff of the Avatar": 20,
  "Staff of the Great Beyond": 2.5,
  "Staff of the Guilty": 4.5,
  "Star Fist": 3,
  "Star-Lined Sword": 5,
  "Starscourge Greatsword": 20,
  "Steel-Wire Torch": 3,
  "Stone Club": 7,
  "Stone-Sheathed Sword": 5,
  "Stormhawk Axe": 5.5,
  "Swift Spear": 3,
  "Sword Lance": 9,
  "Sword of Darkness": 4,
  "Sword of Light": 4,
  "Sword of Milos": 10,
  "Sword of Night": 6.5,
  "Sword of Night and Flame": 4,
  "Sword of St. Trina": 3,
  "Thiollier's Hidden Needle": 0.5,
  "Thorned Whip": 2.5,
  "Tooth Whip": 3,
  Torch: 1.5,
  Torchpole: 6,
  Treespear: 9.5,
  "Troll Knight's Sword": 18,
  "Troll's Golden Sword": 19,
  "Troll's Hammer": 16,
  Twinblade: 7,
  "Twinned Knight Swords": 8,
  Uchigatana: 5.5,
  Urumi: 3,
  "Varré's Bouquet": 2,
  "Velvet Sword of St. Trina": 2.5,
  "Venomous Fang": 2.5,
  "Veteran's Prosthesis": 4,
  "Vulgar Militia Saw": 8,
  "Vulgar Militia Shotel": 8,
  "Vyke's War Spear": 8,
  Wakizashi: 3,
  "Warhawk's Talon": 3,
  "Warped Axe": 7.5,
  Warpick: 2.5,
  "Watchdog's Greatsword": 22,
  "Watchdog's Staff": 19,
  "Weathered Straight Sword": 3,
  Whip: 2,
  "Wing of Astel": 2.5,
  "Winged Greathorn": 11,
  "Winged Scythe": 7.5,
  "Zamor Curved Sword": 9,
  Zweihander: 15.5,
};

const shieldNameToWeight: Record<Weapon["name"], number> = {
  "Smithscript Shield": 2.5,
  "Shield of Night": 2,
  "Messmer Soldier Shield": 5,
  "Wolf Crest Shield": 6,
  "Serpent Crest Shield": 6,
  "Golden Lion Shield": 5.5,
  "Black Steel Greatshield": 19.5,
  "Verdigris Greatshield": 28,
  "Albinauric Shield": 4.5,
  "Ant's Skull Plate": 13.5,
  "Banished Knight's Shield": 6,
  "Beast Crest Heater Shield": 3.5,
  "Beastman's Jar-Shield": 5,
  "Black Leather Shield": 3,
  "Blue Crest Heater Shield": 3.5,
  "Blue-Gold Kite Shield": 5,
  "Blue-White Wooden Shield": 2,
  "Brass Shield": 7,
  "Briar Greatshield": 9.5,
  Buckler: 1.5,
  "Candletree Wooden Shield": 3.5,
  "Carian Knight's Shield": 4.5,
  "Coil Shield": 1.5,
  "Crossed-Tree Towershield": 16,
  "Crucible Hornshield": 11.5,
  "Cuckoo Greatshield": 15,
  "Distinguished Greatshield": 17,
  "Dragon Towershield": 17.5,
  "Dragonclaw Shield": 13.5,
  "Eclipse Crest Greatshield": 15,
  "Eclipse Crest Heater Shield": 3.5,
  "Erdtree Greatshield": 13.5,
  "Fingerprint Stone Shield": 29,
  "Flame Crest Wooden Shield": 3.5,
  "Gilded Greatshield": 17.5,
  "Gilded Iron Shield": 3,
  "Golden Beast Crest Shield": 12.5,
  "Golden Greatshield": 17,
  "Great Turtle Shell": 5.5,
  "Haligtree Crest Greatshield": 18.5,
  "Hawk Crest Wooden Shield": 3.5,
  "Heater Shield": 3.5,
  "Horse Crest Wooden Shield": 3.5,
  "Ice Crest Shield": 3,
  "Icon Shield": 11.5,
  "Inverted Hawk Heater Shield": 3.5,
  "Inverted Hawk Towershield": 16,
  "Iron Roundshield": 3,
  "Jellyfish Shield": 8,
  "Kite Shield": 4.5,
  "Large Leather Shield": 3,
  "Lordsworn's Shield": 10,
  "Man-Serpent's Shield": 2,
  "Manor Towershield": 16,
  "Marred Leather Shield": 3,
  "Marred Wooden Shield": 4,
  "One-Eyed Shield": 20.5,
  "Perfumer's Shield": 1.5,
  "Pillory Shield": 3.5,
  "Red Crest Heater Shield": 3.5,
  "Red Thorn Roundshield": 1.5,
  "Redmane Greatshield": 14,
  "Rickety Shield": 1,
  "Rift Shield": 2,
  "Riveted Wooden Shield": 2,
  "Round Shield": 4,
  "Scorpion Kite Shield": 4.5,
  "Scripture Wooden Shield": 1.5,
  "Shield of the Guilty": 2,
  "Smoldering Shield": 3,
  "Silver Mirrorshield": 3.5,
  "Spiked Palisade Shield": 11.5,
  "Spiralhorn Shield": 2,
  "Sun Realm Shield": 3.5,
  "Twinbird Kite Shield": 4.5,
  "Visage Shield": 24,
  "Wooden Greatshield": 8,
};

const weaponsAndShields = {
  ...weaponNameToWeight,
  ...shieldNameToWeight,
};

export function addWeightToWeapon(weapon: Weapon): Weapon {
  // Seals, Cipha Pata & Unarmed have no weight
  return {
    ...weapon,
    weight: weaponsAndShields[weapon.weaponName],
  };
}
